# Workflow that runs the linter once a PR is approved

name: Linting on approval

on:
  pull_request_review:
    branches: [ "dev" ]
    types: [submitted]
permissions:
  contents: write

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
    - name: Install black
      run: pipx install black
    - name: Run black
      run: black .
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -a -m "Run linter."
        git push

