# Workflow that runs the linter once a PR is approved

name: Linting on approval

on:
  pull_request_review:
    branches: [ "dev" ]
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install black
    - name: Run black
      run: black .
    - name: Commit changes
      run: git commit -a -m "Run linter."

